[build]
  functions = "netlify/functions"
  publish = "src/public"

[build.environment]
  PYTHON_VERSION = "3.12"

[dev]
  command = ""
  publish = "src/public"
  port = 8888
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
